Main svc
pkingsbl/java-explore-with-me pull request #4
Opened 2023-04-17 20:48 UTC by pkingsbl

2023-04-19 06:58 UTC, Fleaman777 requested changes

2023-04-19 06:58 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/repository/EventRepository.java
> +    List<Event> pbcSearchEvents(
не самые понятные нзавания adm... и pbc... если не быть полностью в контексте )
методы должны начинаться с глагола

2023-04-19 06:58 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/service/event/EventServiceImpl.java
> +                                : event.getEventDate().isBefore(LocalDateTime.MAX))
т.к. условие внутри filter достаточно большое, хорошо было бы его вынести в отдельный метод,

подходящее название метода улучшило бы восприятие, т.к. не нужно было бы вдаваться в подробности логики фильтрации, а достаточно было б просто прочитать название метода

2023-04-19 06:58 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/service/event/EventServiceImpl.java
> +    public EventFullDto updateEvent(Long eventId, UpdateEventAdminRequest updateEvent,String requestURI) {
updateEvent,String 
тут не хватает пробела после ,

2023-04-19 06:58 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/service/event/EventServiceImpl.java
> +                                : event.getEventDate().isBefore(LocalDateTime.MAX))
это условие тоже можно было бы вынести во вспомогательный метод

2023-04-19 06:58 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/service/event/EventServiceImpl.java
> +                .build();
```
allById.stream()
                        .map(ParticipationMapper::toParticipationRequestDto)
                        .collect(Collectors.toList()))
                .build();
```

используется в 2х местах,

2023-04-19 06:58 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/service/event/EventServiceImpl.java
> +    }
checkEventDate и checkState, 
должны ли быть статическими методами ?

2023-04-19 06:58 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/service/event/EventServiceImpl.java
> +
а вообще, достаточно хорошее вынесение общей логики в отдельные методы 👍

2023-04-19 06:58 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/service/participation/ParticipationServiceImpl.java
> +        Participation participation = participationRepository.findByIdAndRequesterId(requestId, userId)
аргументы в методе findByIdAndRequesterId(requestId, userId) перепутаны местами

2023-04-19 06:58 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/service/user/UserServiceImpl.java
> +        log.info("Get users " + (ids == null ? null : "with ids: " + ids));
в принципе, лог Get users with ids [null] нормальный, 
и не придеться добавлять тернарный оператор в сам лог

2023-04-19 06:58 UTC, Fleaman777 commented on docker-compose.yml
> +      - stat-client.name=ewm-main-service
хорошо бы придерживаться единого стиля названия и просечивания переменных окружения
т.е. называя их в верхнем регистре
например как SPRING_SERVER_URL

2023-04-19 09:51 UTC, pkingsbl commented on main-service/src/main/java/ru/practicum/service/participation/ParticipationServiceImpl.java
> +        Participation participation = participationRepository.findByIdAndRequesterId(requestId, userId)
requestId - это id request
userId - это id requester
Переименовала для читаемости

2023-04-20 13:41 UTC, Fleaman777 approved these changes

2023-04-24 09:56 UTC, merged